### ISSUE TITLE
Infracost comment Error reading JSON file

### ISSUE THREAD

**Issue by jmreicha** [infracost/infracost-atlantis#43]
Seems I have run into an issue configuring infracost to run with Terraform/Terragrunt. Following the [docs here](https://github.com/infracost/infracost-atlantis/blob/master/examples/combined-infracost-comment/README.md#running-with-github) and basically adapting the config to work with GH.

Receiving the following error:

```
Error running post-workflow hooks exit status 1: running "infracost comment github --repo $BASE_REPO_OWNER/$BASE_REPO_NAME \\\n  --pull-request $PULL_NUM \\\n  --path /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/'*'-infracost.json \\\n  --github-token $ATLANTIS_GH_TOKEN \\\n  --behavior hide-and-new\n" in "/home/atlantis/.atlantis/repos/foo/4532/default": 
[91mError:[0m Error reading JSON file: open /tmp/foo-4532/*-infracost.json: no such file or directory
```

It looks like something doesn't quite look right with the flag syntax on the `comment` command? I have looked and the `/tmp/foo-4532` directory exists but not sure what else I'm missing.

**Comment by jmreicha** [comment]
Investigating further, it looks like the `$INFRACOST_OUTPUT` var is not set (or set to blank).

**Comment by alikhajeh1** [comment]
@jmreicha thanks for creating this issue! Are you using [this Atlantis example](https://github.com/infracost/infracost-atlantis/blob/master/examples/combined-infracost-comment/README.md)? That example shows an Atlantis `env` workflow step to set `INFRACOST_OUTPUT`.

Also, what version of Infracost and Atlantis are you using?

**Comment by jmreicha** [comment]
Thanks for the quick response. As for your questions,

1. I have the env part getting set

```
        - env:
            name: INFRACOST_OUTPUT
            command: 'echo "/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/$WORKSPACE-$REPO_REL_DIR-infracost.json"'
```

2. That directory is showing as empty.
3. Infracost is v0.9 (I think it was 0.9.18). Atlantis is 0.18.2.
4. I am using a custom Dockerfile to put a few extra tools in the image. Basically [these bits](https://github.com/infracost/infracost-atlantis/blob/master/Dockerfile#L5-L9).

**Comment by alikhajeh1** [comment]
Perfect! Can you please:

1. Tweak the step that runs `infracost breakdown` so it outputs the INFRACOST_OUTPUT env to see if that's being set correctly before infracost breakdown runs:

```
- run: echo $INFRACOST_OUTPUT && infracost breakdown --path=$SHOWFILE --format=json --log-level=info --out-file=$INFRACOST_OUTPUT
```

2. In the `post_workflow_hooks` command, tweak it to the following in case that env is not being preserved for some reason:
```
post_workflow_hooks:
      - run: |
          echo $INFRACOST_OUTPUT
          ls -lah $INFRACOST_OUTPUT
          infracost comment github....
```

Let's see if the Atlantis logs give any clues with the above.

**Comment by jmreicha** [comment]
Hrm, not quite what I expected but we have a different error now.

```
Error running post-workflow hooks exit status 1: running "echo $INFRACOST_OUTPUT\nls -lah $INFRACOST_OUTPUT\ninfracost comment github --repo $BASE_REPO_OWNER/$BASE_REPO_NAME \\\n  --pull-request $PULL_NUM \\\n  --path /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/'*'-infracost.json \\\n  --github-token $ATLANTIS_GH_TOKEN \\\n  --behavior hide-and-new\n" in "/home/atlantis/.atlantis/repos/org/foo/4532/default": 

total 580K   
drwx------   22 atlantis atlantis    4.0K Mar  1 02:20 .
drwx------    4 atlantis atlantis    4.0K Mar  1 02:20 ..
drwxr-xr-x    3 atlantis atlantis    4.0K Mar  1 02:20 .terragrunt-stuff
...
[91mError:[0m Error reading JSON file: open /tmp/foo-4532/*-infracost.json: no such file or directory
```

Seems that the env var is empty. Jumped in the container and confirmed that the /tmp/foo-4532 directory is empty.

**Comment by jmreicha** [comment]
Was able to get into the container and run the commands manually and get a comment to post so I think I am overlooking something simple.

**Comment by alikhajeh1** [comment]
So the `INFRACOST_OUTPUT` env is showing as being set ok in the custom workflow stage where `infracost breakdown` is run, but it's showing as empty in the post-workflow-hooks stage?

If so, can you try setting that env again in the post-workflow-hooks stage, like the following:
```
post_workflow_hooks:
      - run: |
          export INFRACOST_OUTPUT=/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/$WORKSPACE-$REPO_REL_DIR-infracost.json"
          echo $INFRACOST_OUTPUT
          ls -lah $INFRACOST_OUTPUT
          infracost comment github --repo $BASE_REPO_OWNER/$BASE_REPO_NAME \
                                    --pull-request $PULL_NUM \
                                    --path /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/'*'-infracost.json \
                                    --github-token $GITHUB_TOKEN \
                                    --behavior new
      - run: rm -rf /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM
```

**Comment by aliscott** [comment]
@jmreicha @alikhajeh1 I've tried to reproduce this but haven't been able to yet with Infracost v0.9.18 and Atlantis v0.18.2. Here's my current thoughts:

1. This is okay: `INFRACOST_OUTPUT` isn't set in the `post_workflow_hooks` - we don't use it in the post workflow hook anyway.
2. This looks like the `infracost breakdown` command isn't saving the JSON output to a file.
  
    > I should also mention that I do see the cost estimation output as a json object at the very bottom of the plan comment so that part is working as expected.

    This is not expected. It should show something like this instead of the JSON output:
    ```
    time="2022-03-01T08:48:31Z" level=info msg="Output saved to /tmp/infracost-atlantis-demo-22/default-terraform-aws-infracost.json"
    ```

Can you paste the `infracost breakdown` command you are using?

**Comment by jmreicha** [comment]
Hi @aliscott Going off the instructions [here](https://github.com/infracost/infracost-atlantis/blob/master/examples/combined-infracost-comment/README.md#running-with-github) I have tried a few different variatons on the following command changing the `--out-file` path.

```
infracost breakdown --path=$SHOWFILE --format=json --log-level=info --out-file=$INFRACOST_OUTPUT
```

Here's my full config if it's helpful.

```
repos:
  - id: /.*/
    workflow: my-wokflow
    # PRs must be approved and in a mergeable state
    apply_requirements: [approved, mergeable]

    # Allow individual repos to define their own workflows
    allow_custom_workflows: true
    allowed_overrides: [apply_requirements, workflow]

    pre_workflow_hooks:
      # Configure terragrunt-atlantis-config
      - run: |
          terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace --ignore-dependency-blocks --workflow my-workflow
      # Clean up any files left over from previous runs
      - run: rm -rf /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM
      - run: mkdir -p /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM

    post_workflow_hooks:
      - run: |
          infracost comment github --repo $BASE_REPO_OWNER/$BASE_REPO_NAME \
            --pull-request $PULL_NUM \
            --path /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/'*'-infracost.json \
            --github-token $ATLANTIS_GH_TOKEN \
            --behavior hide-and-new
      - run: rm -rf /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM

# Manage top level workflows here
workflows:
  infrastructure-live:
    plan:
      steps:
        - env:
            name: TERRAGRUNT_TFPATH
            command: 'echo "terraform${ATLANTIS_TERRAFORM_VERSION}"'
        - env:
            name: INFRACOST_OUTPUT
            command: 'echo "/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/$WORKSPACE-$REPO_REL_DIR-infracost.json"'

        - run: terragrunt plan -no-color -out=$PLANFILE $DESTROY_FLAG
        - run: terragrunt show -json $PLANFILE > $SHOWFILE
        # Run Infracost breakdown and save to a tempfile, namespaced by this project, PR, workspace and dir
        - run: infracost breakdown --path=$SHOWFILE --format=json --log-level=info --out-file=$INFRACOST_OUTPUT
    apply:
      steps:
        - env:
            name: TERRAGRUNT_TFPATH
            command: 'echo "terraform${ATLANTIS_TERRAFORM_VERSION}"'
        - run: terragrunt apply -no-color $PLANFILE
```

@alikhajeh1 I'll try your suggestion later today.
