### ISSUE TITLE
WORKSPACE and REPO_REL_DIR not available on post_workflow_hooks

### ISSUE THREAD

**Issue by brunooon** [infracost/infracost-atlantis#65]
Hello, I was configuring a post_workflow_hooks to add a comment on my PR with Infracost information, but nothing was happening. After debug for a while, I checked the WORKSPACE and REPO_REL_DIR variables were not avail on post_workflow_hooks, so Atlantis couldn’t find the path with the Infracost information to post the comment. My current setup is configured with Altantis + Terragrunt.

Here is some informations bellow:
**terragrunt-infracost:**
```
    plan:
      steps:
        - env:
            name: INFRACOST_OUTPUT
            command: 'echo "/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE-${REPO_REL_DIR//\//-}-infracost.json"'
        - env:
            name: TERRAGRUNT_TFPATH
            command: 'echo "terraform${ATLANTIS_TERRAFORM_VERSION}"'
        - run: terragrunt plan -out=$PLANFILE
        - run: terragrunt show -json $PLANFILE > $SHOWFILE
```

**post_workflow_hooks**:
```
        - run: |
            echo "testing post_workflow_hooks for PR $PULL_NUM" >> /tmp/test.txt
            echo "/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE/'*'-infracost.json"
            # post_workflow_hooks are executed after the repo workflow has run.
            # This enables you to post an Infracost comment with the combined cost output
            # from all your projects. However, post_workflow_hooks are also triggered when
            # an apply occurs. In order to stop commenting on PRs twice we need to check
            # if the Infracost output directory created in our 'plan' stage exists before continuing.
            echo "before if stage exists" >> /tmp/test.txt
            echo "/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE" >> /tmp/test.txt
            echo "WORKSPACE: $WORKSPACE" >> /tmp/test.txt
            echo "REPO_REL_DIR: ${REPO_REL_DIR//\//-}" >> /tmp/test.txt
            if [ ! -d "/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE" ]; then
              exit 0
            fi
            echo "after if stage exists" >> /tmp/test.txt
            # Choose the commenting behavior, 'new' is a good default:
            # new: Create a new cost estimate comment on every run of Atlantis for each project.
            # update: Create a single comment and update it. The "quietest" option.
            # hide-and-new: Minimize previous comments and create a new one.
            # delete-and-new: Delete previous comments and create a new one.
            echo "before infracost comment" >> /tmp/test.txt
            echo "--repo $BASE_REPO_OWNER/$BASE_REPO_NAME" >> /tmp/test.txt
            echo "--pull-request $PULL_NUM" >> /tmp/test.txt
            echo "--path /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE/'*'-infracost.json" >> /tmp/test.txt
            echo "--github-token $GITHUB_TOKEN" >> /tmp/test.txt
            infracost comment github --repo $BASE_REPO_OWNER/$BASE_REPO_NAME \
                                      --pull-request $PULL_NUM \
                                      --path /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE/'*'-infracost.json \
                                      --github-token $GITHUB_TOKEN \
                                      --behavior new
            # remove the Infracost output directory so that `infracost comment` is not
            # triggered on an `atlantis apply`
            echo "before deleting foolder" >> /tmp/test.txt
            rm -rf /tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE
```

**debug output:**
```
bash-5.1$ cat test.txt 
testing post_workflow_hooks for PR 175
before if stage exists
/tmp/org-respository-175-
WORKSPACE: 
REPO_REL_DIR: 
after if stage exists
before infracost comment
--repo org/repository
--pull-request 175
--path /tmp/org-repository-175-/'*'-infracost.json
--github-token 123456
```

As a workaround to solve this issue, I stoped using WORKSPACE on my infracost output and I created a single folder for my PR  `/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/` with all outputs inside.
