### ISSUE TITLE
[Doubt] How to use Github + Terragrunt

### ISSUE THREAD

**Issue by weyderfs** [infracost/infracost-atlantis#70]
I'm following the docs, but I'm confuse about how to setup the `post_workflow_hook` together with Terragrunt setup.

My `repoConfig`:
```yaml

repoConfig: |
  repos:
  - id: "/.*/"
    workflow: terragrunt
    pre_workflow_hooks: #TGENV and TFENV setup
      - run: git clone --depth=1 https://github.com/tfutils/tfenv.git /home/atlantis/.tfenv && git clone https://github.com/cunymatthieu/tgenv.git /home/atlantis/.tgenv
      - run: chmod -R +x .tgenv/bin .tfenv/bin
  workflows:
    terragrunt:
      plan:
        steps:
        - env:
            name: INFRACOST_OUTPUT
            command: 'echo "/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM/$WORKSPACE-${REPO_REL_DIR//\//-}-infracost.json"'
        - env:
            name: TERRAGRUNT_TFPATH
            command: 'echo "terraform${ATLANTIS_TERRAFORM_VERSION}"'        
        - env:
            name: PATH #Set PATH of binaries of TGenv and TFenv at atlantis user /home
            command: 'echo "${PATH}:${HOME}/.tgenv/bin:${HOME}/.tfenv/bin"'
        - run: echo "Setup Terragrunt version if necessary"
        - run: tgenv install
        - run: echo "Running Terragrunt Plan now!"        
        - run: terragrunt plan -input=false -out=$PLANFILE
        - run: terragrunt show -json $PLANFILE > $SHOWFILE
      apply:
        steps:
        - env:
            name: PATH
            command: 'echo "${PATH}:${HOME}/.tgenv/bin:${HOME}/.tfenv/bin"'
        - run: terragrunt apply -input=false $PLANFILE
```

Because in this [example](https://github.com/infracost/infracost-atlantis/blob/master/examples/combined-infracost-comment/README.md#running-with-github) is about running with Terraform.

Someone can help to understand better?

## Update 1

After run the `altantis plan` in my _pull-request_ returns:

```
running "infracost breakdown --path=$PLANFILE --format=json --out-file=/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE-$REPO_REL_DIR-infracost.json" in "/atlantis-data/repos/TiendaNube/terragrunt/47/default/providers/aws/linkedstore/stg/us-west-2/engenharia/sre/sqs-apresentacao": exit status 1: running "infracost breakdown --path=$PLANFILE --format=json --out-file=/tmp/$BASE_REPO_OWNER-$BASE_REPO_NAME-$PULL_NUM-$WORKSPACE-$REPO_REL_DIR-infracost.json" in "/atlantis-data/repos/TiendaNube/terragrunt/47/default/providers/aws/linkedstore/stg/us-west-2/engenharia/sre/sqs-apresentacao": 
time="2022-12-08T00:52:08Z" level=info msg="Detected Terraform plan binary file at /atlantis-data/repos/TiendaNube/terragrunt/47/default/providers/aws/linkedstore/stg/us-west-2/engenharia/sre/sqs-apresentacao/default.tfplan"

Error: Could not detect Terraform directory for /atlantis-data/repos/TiendaNube/terragrunt/47/default/providers/aws/linkedstore/stg/us-west-2/engenharia/sre/sqs-apresentacao/default.tfplan.
Either the current working directory or the plan file's parent directory must be a Terraform directory.

If the above does not work you can generate the plan JSON file with:
terraform show -json tfplan.binary > plan.json
and then run Infracost with --path=plan.json

[...]
```
